
name: Add List to task

on:
  issues:
    label:
      name: task

jobs:
  issue_list:
    runs-on: ubuntu-latest

    steps:
    - name: Edit description of issue
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'update-issue'
        body: '- item 1\n- item 2\n- item 3'
        update-mode: 'replace'
